
---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, output-file: index.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns index
  (:require [tablecloth.api :as tc]
            [tablecloth.column.api :as tcc]
            [scicloj.noj.v1.vis.hanami :as hanami]
            [aerial.hanami.templates :as ht]
            [tech.v3.dataset.categorical :as ds-cat]
            [tech.v3.dataset.modelling :as ds-mod]
            [tech.v3.dataset.column-filters :as cf]
            [scicloj.kindly.v4.kind :as kind]
            [scicloj.metamorph.core :as morph]
            [tablecloth.api.split :as split]
            [scicloj.metamorph.ml :as ml]
            [tech.v3.dataset :as tds]
            [camel-snake-kebab.core :as csk]
            [scicloj.metamorph.ml.loss :as loss]
            [scicloj.ml.smile.classification]))
```
:::



#### Fetching data


::: {.sourceClojure}
```clojure
(def ds
  (-> "data/index.csv"
      (tc/dataset {:key-fn keyword})))
```
:::



::: {.sourceClojure}
```clojure
(tc/unique-by ds :coffee_name)
```
:::


::: {.clay-dataset}
data/index.csv [8 6]:

|      :date |               :datetime | :cash_type |               :card | :money |        :coffee_name |
|------------|-------------------------|------------|---------------------|-------:|---------------------|
| 2024-03-01 | 2024-03-01 10:15:50.520 |       card | ANON-0000-0000-0001 |   38.7 |               Latte |
| 2024-03-01 | 2024-03-01 12:19:22.539 |       card | ANON-0000-0000-0002 |   38.7 |       Hot Chocolate |
| 2024-03-01 | 2024-03-01 13:46:33.006 |       card | ANON-0000-0000-0003 |   28.9 |           Americano |
| 2024-03-01 | 2024-03-01 15:39:47.726 |       card | ANON-0000-0000-0005 |   33.8 | Americano with Milk |
| 2024-03-01 | 2024-03-01 19:22:01.762 |       card | ANON-0000-0000-0008 |   38.7 |               Cocoa |
| 2024-03-03 | 2024-03-03 11:33:56.118 |       card | ANON-0000-0000-0016 |   28.9 |             Cortado |
| 2024-03-04 | 2024-03-04 14:04:37.734 |       card | ANON-0000-0000-0022 |   24.0 |            Espresso |
| 2024-03-06 | 2024-03-06 14:52:01.761 |       card | ANON-0000-0000-0029 |   38.7 |          Cappuccino |


:::



#### Feature engineering


::: {.sourceClojure}
```clojure
(defn coffee-has-milk [str]
  (boolean (some #(= str %) ["Latte" "American With Milk" "Cortado" "Cappuccino"])))
```
:::



::: {.sourceClojure}
```clojure
(defn coffee-has-chocolate [str]
  (boolean (some #(= str %) ["Cocoa" "Hot Chocolate"])))
```
:::



::: {.sourceClojure}
```clojure
(def coffee-names
  (distinct (apply list (:coffee_name ds))))
```
:::



::: {.sourceClojure}
```clojure
coffee-names
```
:::



::: {.printedClojure}
```clojure
("Latte"
 "Hot Chocolate"
 "Americano"
 "Americano with Milk"
 "Cocoa"
 "Cortado"
 "Espresso"
 "Cappuccino")

```
:::



::: {.sourceClojure}
```clojure
(def with-features
  (-> ds
      (tc/add-column :with-milk
                     (fn [dataset]
                       (map
                        (fn [name] (coffee-has-milk name))
                        (:coffee_name ds))))
      (tc/add-column :with-chocolate
                     (fn [dataset]
                       (map
                        (fn [name] (coffee-has-chocolate name))
                        (:coffee_name ds))))))
```
:::



::: {.sourceClojure}
```clojure
(def categorical-feature-columns [:coffee_name :with-milk :with-chocolate])
```
:::



::: {.sourceClojure}
```clojure
(def target-column :cash_type)
```
:::



::: {.sourceClojure}
```clojure
(map
 #(hash-map
   :col-name %
   :values  (distinct (get with-features %)))
 categorical-feature-columns)
```
:::



::: {.printedClojure}
```clojure
({:col-name :coffee_name,
  :values
  ("Latte"
   "Hot Chocolate"
   "Americano"
   "Americano with Milk"
   "Cocoa"
   "Cortado"
   "Espresso"
   "Cappuccino")}
 {:col-name :with-milk, :values (true false)}
 {:col-name :with-chocolate, :values (false true)})

```
:::



::: {.sourceClojure}
```clojure
(tc/column-names with-features)
```
:::



::: {.printedClojure}
```clojure
(:date
 :datetime
 :cash_type
 :card
 :money
 :coffee_name
 :with-milk
 :with-chocolate)

```
:::



::: {.sourceClojure}
```clojure
(tds/descriptive-stats with-features)
```
:::


::: {.clay-dataset}
data/index.csv: descriptive-stats [8 12]:

|       :col-name |          :datatype | :n-valid | :n-missing |       :min |      :mean |                   :mode |       :max | :standard-deviation |       :skew |                  :first |                   :last |
|-----------------|--------------------|---------:|-----------:|------------|------------|-------------------------|------------|--------------------:|------------:|-------------------------|-------------------------|
|           :date | :packed-local-date |     1133 |          0 | 2024-03-01 | 2024-05-19 |                         | 2024-07-31 |      3.84601753E+09 | -0.08504978 |              2024-03-01 |              2024-07-31 |
|       :datetime |            :string |     1133 |          0 |            |            | 2024-06-09 15:10:30.692 |            |                     |             | 2024-03-01 10:15:50.520 | 2024-07-31 21:55:16.570 |
|      :cash_type |            :string |     1133 |          0 |            |            |                    card |            |                     |             |                    card |                    card |
|           :card |            :string |     1044 |         89 |            |            |                         |            |                     |             |     ANON-0000-0000-0001 |     ANON-0000-0000-0446 |
|          :money |           :float64 |     1133 |          0 |      18.12 |      33.11 |                         |      40.00 |      5.03536551E+00 | -0.55911986 |                   38.70 |                   32.82 |
|    :coffee_name |            :string |     1133 |          0 |            |            |     Americano with Milk |            |                     |             |                   Latte |                   Latte |
|      :with-milk |           :boolean |     1133 |          0 |            |            |                   false |            |                     |             |                    true |                    true |
| :with-chocolate |           :boolean |     1133 |          0 |            |            |                   false |            |                     |             |                   false |                   false |


:::



::: {.sourceClojure}
```clojure
(-> with-features
    (:with-milk)
    frequencies)
```
:::



::: {.printedClojure}
```clojure
{true 538, false 595}

```
:::



#### Preparing the features to be fit into a model


::: {.sourceClojure}
```clojure
(def relevant-with-features-ds
  (-> with-features
      (tc/select-columns (conj categorical-feature-columns target-column))
      (tds/drop-missing)
      (tds/categorical->number [target-column] ["card" "cash"] :float64)
      (ds-mod/set-inference-target target-column)))
```
:::



::: {.sourceClojure}
```clojure
(def cat-maps
  [
   (ds-cat/fit-categorical-map relevant-with-features-ds :coffee_name coffee-names :float64)
   (ds-cat/fit-categorical-map relevant-with-features-ds :with-milk [true false] :float64)
   (ds-cat/fit-categorical-map relevant-with-features-ds :with-chocolate [true false] :float64)
   ])
```
:::



::: {.sourceClojure}
```clojure
cat-maps
```
:::



::: {.printedClojure}
```clojure
[{:lookup-table
  {"Latte" 0,
   "Hot Chocolate" 1,
   "Americano" 2,
   "Americano with Milk" 3,
   "Cocoa" 4,
   "Cortado" 5,
   "Espresso" 6,
   "Cappuccino" 7},
  :src-column :coffee_name,
  :result-datatype :float64}
 {:lookup-table {true 0, false 1},
  :src-column :with-milk,
  :result-datatype :float64}
 {:lookup-table {true 0, false 1},
  :src-column :with-chocolate,
  :result-datatype :float64}]

```
:::



::: {.sourceClojure}
```clojure
(def numeric-ds
  (reduce (fn [ds cat-map]
            (ds-cat/transform-categorical-map ds cat-map))
          relevant-with-features-ds
          cat-maps))
```
:::



::: {.sourceClojure}
```clojure
(tc/head numeric-ds 500)
```
:::


::: {.clay-dataset}
data/index.csv [500 4]:

| :coffee_name | :with-milk | :with-chocolate | :cash_type |
|-------------:|-----------:|----------------:|-----------:|
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        1.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          4.0 |        1.0 |             0.0 |        1.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        1.0 |
|          1.0 |        1.0 |             0.0 |        1.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        1.0 |
|          1.0 |        1.0 |             0.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        1.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          4.0 |        1.0 |             0.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        1.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          5.0 |        0.0 |             1.0 |        0.0 |
|          6.0 |        1.0 |             1.0 |        0.0 |
|          7.0 |        0.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        1.0 |
|          7.0 |        0.0 |             1.0 |        1.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          1.0 |        1.0 |             0.0 |        0.0 |
|          0.0 |        0.0 |             1.0 |        0.0 |
|          2.0 |        1.0 |             1.0 |        0.0 |
|          3.0 |        1.0 |             1.0 |        0.0 |


:::



#### Mounting the model


::: {.sourceClojure}
```clojure
(def split
  (first
   (tc/split->seq numeric-ds :holdout {:seed 112723})))
```
:::



::: {.sourceClojure}
```clojure
split
```
:::



```{=html}
<div><p>{</p><div class="clay-map" style="margin-left:10%;width:110%;"><table><tr><td valign="top"><div><pre><code class="sourceCode language-clojure printed-clojure">:train
</code></pre></div></td><td><div style="margin-left:10px;"><div class="clay-dataset"><p>Group: 0 [755 4]:</p><table class="table"><thead><tr><th style="text-align:right;">:coffee_name</th><th style="text-align:right;">:with-milk</th><th style="text-align:right;">:with-chocolate</th><th style="text-align:right;">:cash_type</th></tr></thead><tbody><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">6.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">5.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">5.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">...</td><td style="text-align:right;">...</td><td style="text-align:right;">...</td><td style="text-align:right;">...</td></tr><tr><td style="text-align:right;">5.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">5.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">6.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr></tbody></table></div></div></td></tr></table><table><tr><td valign="top"><div><pre><code class="sourceCode language-clojure printed-clojure">:test
</code></pre></div></td><td><div style="margin-left:10px;"><div class="clay-dataset"><p>Group: 0 [378 4]:</p><table class="table"><thead><tr><th style="text-align:right;">:coffee_name</th><th style="text-align:right;">:with-milk</th><th style="text-align:right;">:with-chocolate</th><th style="text-align:right;">:cash_type</th></tr></thead><tbody><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td></tr><tr><td style="text-align:right;">...</td><td style="text-align:right;">...</td><td style="text-align:right;">...</td><td style="text-align:right;">...</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">0.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">5.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">2.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">3.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">0.0</td></tr><tr><td style="text-align:right;">7.0</td><td style="text-align:right;">0.0</td><td style="text-align:right;">1.0</td><td style="text-align:right;">1.0</td></tr></tbody></table></div></div></td></tr></table></div><p>}</p></div>
```


https://scicloj.github.io/noj/noj_book.ml_basic.html#train-a-model


::: {.sourceClojure}
```clojure
(def model-with-logistic-regression
  (ml/train (:train split) {:model-type :smile.classification/logistic-regression}))
```
:::



::: {.sourceClojure}
```clojure
model-with-logistic-regression
```
:::



::: {.printedClojure}
```clojure
{:model-data
 {:smile-df-used
  [coffee_name: double, with-milk: double, with-chocolate: double, cash_type: int]
+-----------+---------+--------------+---------+
|coffee_name|with-milk|with-chocolate|cash_type|
+-----------+---------+--------------+---------+
|          0|        0|             1|        0|
|          6|        1|             1|        1|
|          2|        1|             1|        0|
|          5|        0|             1|        0|
|          5|        0|             1|        0|
|          3|        1|             1|        0|
|          7|        0|             1|        0|
|          1|        1|             0|        1|
|          7|        0|             1|        0|
|          1|        1|             0|        0|
+-----------+---------+--------------+---------+
745 more rows...
,
  :smile-props-used
  {"smile.logistic.lambda" "0.1", "smile.logistic.max.iterations" "500", "smile.logistic.tolerance" "1.0E-5"},
  :smile-formula-used
  #object[smile.data.formula.Formula 0x45fb1bf0 "cash_type ~ coffee_name + with-milk + with-chocolate"],
  :model-as-bytes
  [-84, -19, 0, 5, 115, 114, 0, 48, 115, 109, 105, 108, 101, 46, 99,
   108, 97, 115, 115, 105, 102, 105, 99, 97, 116, 105, 111, 110, 46,
   76, 111, 103, 105, 115, 116, 105, 99, 82, 101, 103, 114, 101, 115,
   115, 105, 111, 110, 36, 66, 105, 110, 111, 109, 105, 97, 108, -92,
   -95, -106, -117, 126, 118, 16, -86, 2, 0, 1, 91, 0, 1, 119, 116, 0,
   2, 91, 68, 120, 114, 0, 39, 115, 109, 105, 108, 101, 46, 99, 108,
   97, 115, 115, 105, 102, 105, 99, 97, 116, 105, 111, 110, 46, 76,
   111, 103, 105, 115, 116, 105, 99, 82, 101, 103, 114, 101, 115, 115,
   105, 111, 110, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 6, 68, 0, 1, 76, 68, 0,
   3, 101, 116, 97, 73, 0, 1, 107, 68, 0, 6, 108, 97, 109, 98, 100, 97,
   73, 0, 1, 112, 76, 0, 6, 108, 97, 98, 101, 108, 115, 116, 0, 19, 76,
   115, 109, 105, 108, 101, 47, 117, 116, 105, 108, 47, 73, 110, 116,
   83, 101, 116, 59, 120, 112, -64, 103, -51, -122, 82, 56, -70, 98,
   63, 33, 92, 75, -82, 89, -20, 16, 0, 0, 0, 2, 63, -71, -103, -103,
   -103, -103, -103, -102, 0, 0, 0, 3, 115, 114, 0, 17, 115, 109, 105,
   108, 101, 46, 117, 116, 105, 108, 46, 73, 110, 116, 83, 101, 116, 0,
   0, 0, 0, 0, 0, 0, 2, 2, 0, 4, 73, 0, 3, 109, 97, 120, 73, 0, 3, 109,
   105, 110, 76, 0, 5, 105, 110, 100, 101, 120, 116, 0, 15, 76, 106,
   97, 118, 97, 47, 117, 116, 105, 108, 47, 77, 97, 112, 59, 91, 0, 6,
   118, 97, 108, 117, 101, 115, 116, 0, 2, 91, 73, 120, 112, 0, 0, 0,
   1, 0, 0, 0, 0, 115, 114, 0, 17, 106, 97, 118, 97, 46, 117, 116, 105,
   108, 46, 72, 97, 115, 104, 77, 97, 112, 5, 7, -38, -63, -61, 22, 96,
   -47, 3, 0, 2, 70, 0, 10, 108, 111, 97, 100, 70, 97, 99, 116, 111,
   114, 73, 0, 9, 116, 104, 114, 101, 115, 104, 111, 108, 100, 120,
   112, 63, 64, 0, 0, 0, 0, 0, 12, 119, 8, 0, 0, 0, 16, 0, 0, 0, 2,
   115, 114, 0, 17, 106, 97, 118, 97, 46, 108, 97, 110, 103, 46, 73,
   110, 116, 101, 103, 101, 114, 18, -30, -96, -92, -9, -127, -121, 56,
   2, 0, 1, 73, 0, 5, 118, 97, 108, 117, 101, 120, 114, 0, 16, 106, 97,
   118, 97, 46, 108, 97, 110, 103, 46, 78, 117, 109, 98, 101, 114,
   -122, -84, -107, 29, 11, -108, -32, -117, 2, 0, 0, 120, 112, 0, 0,
   0, 0, 113, 0, 126, 0, 13, 115, 113, 0, 126, 0, 11, 0, 0, 0, 1, 113,
   0, 126, 0, 14, 120, 117, 114, 0, 2, 91, 73, 77, -70, 96, 38, 118,
   -22, -78, -91, 2, 0, 0, 120, 112, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,
   1, 117, 114, 0, 2, 91, 68, 62, -90, -116, 20, -85, 99, 90, 30, 2, 0,
   0, 120, 112, 0, 0, 0, 4, -65, -82, 44, 43, -63, 63, -123, 111, -65,
   -37, 49, 103, 77, 71, -111, 61, -65, -63, 118, 51, 15, 91, 85, -31,
   -64, 0, -86, -53, 91, 32, 50, 123]},
 :options {:model-type :smile.classification/logistic-regression},
 :id #uuid "8449acf1-a946-446a-89f3-0d36c0186d9a",
 :feature-columns [:coffee_name :with-milk :with-chocolate],
 :target-columns [:cash_type],
 :target-categorical-maps
 {:cash_type
  {:lookup-table {"card" 0, "cash" 1},
   :src-column :cash_type,
   :result-datatype :float64}}}

```
:::



::: {.sourceClojure}
```clojure
(def prediction-with-logistic-regression
  (ml/predict (:test split) model-with-logistic-regression))
```
:::



#### Measuring model accuracy

Accuracy of a logistic regression


::: {.sourceClojure}
```clojure
(loss/classification-accuracy
 (:cash_type (ds-cat/reverse-map-categorical-xforms (:test split)))
 (:cash_type (ds-cat/reverse-map-categorical-xforms prediction-with-logistic-regression)))
```
:::



::: {.printedClojure}
```clojure
0.9047619047619048

```
:::



::: {.sourceClojure}
```clojure
(def rf-model
  (ml/train (:train split) {:model-type :smile.classification/random-forest}))
```
:::



::: {.sourceClojure}
```clojure
(def rf-prediction
  (ml/predict (:test split) rf-model))
```
:::


Accuracy of a random forest model


::: {.sourceClojure}
```clojure
(loss/classification-accuracy
 (:cash_type (ds-cat/reverse-map-categorical-xforms (:test split)))
 (:cash_type (ds-cat/reverse-map-categorical-xforms rf-prediction)))
```
:::



::: {.printedClojure}
```clojure
0.9047619047619048

```
:::



::: {.sourceClojure}
```clojure
(->>
 (map
  (fn [predictor importance]
    (hash-map :predictor (-> predictor str csk/->kebab-case-keyword)
              :importance importance))
  (-> rf-model ml/thaw-model .formula .predictors)
  (-> rf-model ml/thaw-model .importance))
 (sort-by :importance)
 reverse)
```
:::



::: {.printedClojure}
```clojure
({:predictor :coffee-name, :importance 0.07719322157865996}
 {:predictor :with-chocolate, :importance 0.002974074900820328}
 {:predictor :with-milk, :importance 0.0})

```
:::


We conclude that although a model with ~90% accuracy was built. Not a single of it's features holds
a relevant relationship to the target.

This means that it's hard to guess if you will pay cash or card if we know what type of coffee you're getting. And wether or not it has milk or chocolate in it


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: src/index.clj</small></small></pre></div>
```
